name: prompthub_online
description: PromptHub online - uses Firebase Firestore
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
